### ISSUE TITLE
Freesync2_VK hits multiple asserts

### ISSUE THREAD

**Issue by pmw12345** [GPUOpen-LibrariesAndSDKs/FreesyncPremiumProSample#1]
The program allocates VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC in the descriptor sets but doesn't add any to the pool. This causes an out of pool memory error which asserts and dies. I fixed it in my version by adding VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC with 20 descriptors (wag) in ResourceViewHeaps::OnCreate  this got past that assert. But then the program immediately asserts in the SwapChain::Present function with the error "VK_ERROR_FULLSCREEN_EXCLUSIVE_MODE_LOST". Which it should get this error since it starts out in windowed mode anyway. I got around this with the time tested method of ignoring the error all together. ie 

        if (res != VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT) {
            assert(res == VK_SUCCESS);
        }

**Comment by Meith** [comment]
Hi @pmw12345, your fixes for the pool memory error are correct. We have updated our HDR tone and gamut mapping sample: [FidelityFX-LPM](https://github.com/GPUOpen-Effects/FidelityFX-LPM) with these fixes, including changes on how to manage the Full Screen Exclusive extension structures to avoid hitting the assert in SwapChain::Present. Please feel free to refer to that sample. We are happy to address any new issues there. Closing this one here as this sample will not receive new updates.

**Comment by pmw12345** [comment]
Thanks! I'll switch to the FidelityFX-LPM sample.
